//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assets
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonentsAddress
    {
        public int id { get; set; }
        public int id_abonent { get; set; }
        public string residence { get; set; }
        public string habitation { get; set; }
    
        public virtual Abonent Abonent { get; set; }
    }
}
